name: Run Tests
on:
  pull_request:
    branches:
      - development
      - quality-assurance
      - main
jobs:
  build-and-run-tests:
    uses: ./.github/workflows/run-node-tests.yml

  generate-code-coverage:
    uses: ./.github/workflows/run-generate-code.yml
    with:
      node-version: 20.x
