name: Run tests
on:
  pull_request:
    branches:
      - development
      - quality-assurance
      - main
jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/run-node-tests.yml

  generate-upload-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data-kernel
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run the tests and generate coverage report
        run: |
          npm install
          npm test -- --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
