name: Run tests
on:
  pull_request:
    branches:
      - development
      - quality-assurance
      - main
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data-kernel
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and test
        env:
          CI: false
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Run the tests and generate coverage report
        run: npm test -- --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # files: ./coverage1.xml,./coverage2.xml # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
